font_family FiraCode Nerd Font Mono
bold_font auto
italic_font FiraCode Nerd Font Mono
bold_italic_font FiraCode Nerd Font Mono
font_size 12.0

window_padding_width 0
hide_window_decorations titlebar-and-corners
enable_audio_bell no
confirm_os_window_close 0
shell_integration disabled
allow_hyperlinks no
sync_to_monitor yes

include current-theme.conf

map cmd+w discard_event

map cmd+opt+up send_text all \e[25~
map cmd+opt+down send_text all \e[26~
map ctrl+shift+up send_text all \e[25~
map ctrl+shift+down send_text all \e[26~
map ctrl+shift+k send_text all \e[25~
map ctrl+shift+j send_text all \e[26~

map cmd+opt+left send_text all \e[28~
map cmd+opt+right send_text all \e[29~
map ctrl+shift+left send_text all \e[28~
map ctrl+shift+right send_text all \e[29~
map ctrl+shift+h send_text all \e[28~
map ctrl+shift+l send_text all \e[29~

map cmd+1 send_text all \e[31~
map cmd+2 send_text all \e[32~
map cmd+3 send_text all \e[33~
map cmd+4 send_text all \e[34~
map cmd+5 send_text all \e[35~
map cmd+6 send_text all \e[36~
map cmd+7 send_text all \e[37~
map cmd+8 send_text all \e[38~
map cmd+9 send_text all \e[39~
