name: workspace

on: [push]

jobs:
  workspace-macOS:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1

    - name: Workspace
      run: |
        export HOMEBREW_NO_AUTO_UPDATE=1
        make os=mac

  workspace-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install tmux
      run: make

  go-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install golang
      run: make go

  go-macOs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install golang
      run: make go os=mac
