name: workspace

on:
  push:
    paths:
      - 'Makefile'

jobs:
  workspace-macOS:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1

    - name: Workspace
      run: |
        export HOMEBREW_NO_AUTO_UPDATE=1
        make OS=mac

  workspace-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install tmux
      run: make
