name: workspace

on:
  push:

jobs:
  workspace:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup from lockfile
        run: |
          if [ "$RUNNER_OS" = "macOS" ]; then
            export HOMEBREW_NO_AUTO_UPDATE=1
            export HOMEBREW_NO_ENV_HINTS=1
          fi
          make setup

      - name: Neovim smoke tests after lockfile setup
        run: make nvim-test

      - name: Update latest plugins
        run: |
          if [ "$RUNNER_OS" = "macOS" ]; then
            export HOMEBREW_NO_AUTO_UPDATE=1
            export HOMEBREW_NO_ENV_HINTS=1
          fi
          make update

      - name: Neovim smoke tests after latest update
        run: make nvim-test
